--- AVL Agentproperties PINs definitions
--
avlPropertiesPINs = {
			stationarySpeedThld = 1,
			stationaryDebounceTime = 2,
			movingDebounceTime = 3,
			defaultSpeedLimit = 5,
      speedingTimeOver = 6,
      speedingTimeUnder = 7,
      stationaryIntervalSat = 11,
      movingIntervalSat = 12,
      positionMsgInterval = 26,
      lpmTrigger = 31,
      avlStates = 41,
      digStatesDefBitmap =  46,
      funcDigInp1 = 47,
      funcDigInp2 = 48,
      funcDigInp3 = 49,
      funcDigInp4 = 50,
      funcDigInp5 = 51,
      funcDigInp6 = 52,
      funcDigInp7 = 53,
      funcDigInp8 = 54,
      port1Config = 1,
      port1EdgeDetect = 4,
      port1EdgeSampleCount = 5,
      port2Config = 12,
      port2EdgeDetect = 15,
      port2EdgeSampleCount = 16,
      port3Config = 23,
      port3EdgeDetect = 26,
      port3EdgeSampleCount = 27,
      port4Config = 34,
      port4EdgeDetect = 37,
      port4EdgeSampleCount = 38,
      maxIdlingTime = 23,
      seatbeltDebounceTime = 115,
      lpmEntryDelay = 32,
      funcDigInp13 = 59,
      extPowerPresentStateDetect = 5,
      extPowerPresent = 8,
      turnThreshold = 16,
      turnDebounceTime = 17,
      geofenceEnabled = 1,
      geofenceInterval = 2,
      geofenceHisteresis = 3,
      defaultGeoDwellTime = 25,
      deleteData = 201,
      maxDrivingTime = 20,
      minRestTime = 21,
      odometerDistanceIncrement = 14,
      odometer = 15,
      distanceCellThld = 18,
      distanceSatThld = 19,
      loggingPositionsInterval = 8,
      digPorts = 24



									}
return avlPropertiesPINs
